version: '2'

services:
  icecast:
    build: ./icecast
    ports:
      - "8000:8000"
    networks:
      - music_stack

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    build: ./mpd
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /data/radio/music:/var/lib/mpd/music
      - /data/radio/playlists:/var/lib/mpd/playlists
      - /data/radio/database:/var/lib/mpd/database

  sima:
    build: ./sima
    depends_on:
      - mpd
    networks:
      - music_stack

  ympd:
    build: ./ympd
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

# If you use your own volumes instead host volumes, uncomment this section
volumes:
  mpd_music:
    external: true
  mpd_playlists:
    external: true
  mpd_database:
    external: true


